### ISSUE TITLE
추천목록에 중복된 값이 섞여서 반환됩니다.

### ISSUE THREAD

**Issue by simsosimso** [WebtoonRecommend/MainApiServer#1]
# 🚲 추천 api 사용시, 반환값인 추천목록에 중복된 값이 존재합니다.
![image](https://user-images.githubusercontent.com/76871737/203517828-f03637b7-e702-4301-a0ac-d6dc995b81ed.png)
get recommend api로 추천 목록 요청했습니다.

![image](https://user-images.githubusercontent.com/76871737/203517884-27d4c82b-3393-4002-bd2e-245e0242cf78.png)
그런데 리스트 3, 4번 보시면 중복된 웹툰제목이 있습니다.

**Comment by ChoeMunSeok** [comment]
추천 함수에서 중복값을 제거하는 부분을 추가하여 해결하였습니다.
