### ISSUE TITLE
웹툰 정보를 get할 때 실패합니다.

### ISSUE THREAD

**Issue by simsosimso** [WebtoonRecommend/MainApiServer#2]
GET /WebToon/Title api에서, jwt와 title을 올바르게 입력하여 request를 보냈으나 500 INTERNAL SERVER ERROR가 반환되었습니다.
![image](https://user-images.githubusercontent.com/76871737/205423050-2a98d284-bce5-4367-94f5-88d02fa383c1.png)
![image](https://user-images.githubusercontent.com/76871737/205423123-6b063e45-3292-4708-908c-1b6af6f408a0.png)

**Comment by ChoeMunSeok** [comment]
Authorization의 jwt 토큰을 입력할 때에는 Bearer jwt의 형태로 입력하여야 합니다. 그렇게 하셨나요? Response의 Authorization 헤더를 보시면 그렇게 하지 않으신 것 같습니다.

**Comment by simsosimso** [comment]
그렇네요. 값이 올바르게 나오는 것을 확인하였습니다!
