### ISSUE TITLE
추천 웹툰을 get할 때 실패합니다.

### ISSUE THREAD

**Issue by simsosimso** [WebtoonRecommend/MainApiServer#3]
GET /Recommended/days api에서, jwt와 days를 올바르게 입력하여 request를 보냈으나 500 INTERNAL SERVER ERROR가 반환되었습니다.
![image](https://user-images.githubusercontent.com/76871737/205482949-a0ee983b-0bea-4a84-ab30-030aea108d96.png)
![image](https://user-images.githubusercontent.com/76871737/205482992-6c2d39dc-5d2a-489a-ac3a-5a2a7247b478.png)

**Comment by ChoeMunSeok** [comment]
해당 문제는 gunicorn 웹서버에 의해 발생한 문제로 gunicorn이 오류 메시지를 반환하도록 변경하여 해결하였습니다.
